### ISSUE TITLE
Mocking inherited methods from super class

### ISSUE THREAD

**Issue by lennartblom** [kaste/mockito-python#12]
I currently get weird error messages while testing my business logic in my controller classes.

My project/controller looks like this:

```python
class ControllerBase:
    pass

class RequestControllerBase(ControllerBase):
    # I already have tests for this... 
    def _request_data_validation(...):
        """ request data validation. Returns request data """

class UserSessionRequestControllerBase(RequestControllerBase):
    # I already have tests for this... 
    def _user_session_validation(...):
        """ user session validation. Returns of user id """

class SpecificControllerImplemention(UserSessionRequestControllerBase):
    # I want to write tests for this and mock out the existing methods in super classes
    def business_login(request: Request):
        user_id = self._user_session_validation(request)
        request_data = self._request_data_validation(request)
        # now the business logic follows
        # ....
```

When trying to mock self._request_data_validation(request) with *when()* I get the following error:

```
E           You called
E           
E                   _validate_request_data(request=<DummyRequest id=4402099424>, validation_schema=<UpdateDataSchema(many=False, strict=False)>),
E           
E           which is not expected. Stubbed invocations are:
E           
E                   _validate_request_data(request=<DummyRequest id=4402099424>, validation_schema=<UpdateDataSchema(many=False, strict=False)>)
E      

```

What am I doing wrong? Or is it an issue on the side of mockito's when fixture?
I am using Python 3.6 and pytest.

Thanks it advance!

**Comment by kaste** [comment]
Admitted, that doesn't seem to be a helpful error message, but mockito does simple equality testing for the arguments. The first argument seems to be a mockito dummy. Since they have the same id, they should be equal. The second argument only has the same string repr, so although they could have the same 'meaning'/'state' I would assume - just from reading that line - they are different objects. 

Of course that's just a bit of guessing bc you don't provide enough code. Eg the method mockito complains about doesn't even show up in your source code sample.

**Comment by lennartblom** [comment]
Thank you very much for the reply!
Sorry for submitting so few information. I could not copy the whole example and just wanted to give you an idea what structure I am talking about. 

The string repr seems like a solid hint! I'll try this and get back to you! 

Thanks for the quick and helpful feedback, I appreciate it!

**Comment by lennartblom** [comment]
The string-repr tricked me...
Mocking the method works like a charm, when using the same validating schema object.
Sorry for the inconvenience and thank you very much for the quick support.

In the future I'll be careful while passing initialized objects for mocked methods 👍 

Keep up the good work! Thanks a lot!
