### ISSUE TITLE
Mocking attributes which initially value None

### ISSUE THREAD

**Issue by aaltat** [kaste/mockito-python#13]
If I have this code: 
```
from selenium import webdriver

from mockito import mock, when


class ClassName(object):

    driver = None

    def create_driver(self, browser):
        if browser == 'chrome':
            self.driver = webdriver.Chrome()
        else:
            self.driver = webdriver.Firefox()

    def find_element(self, selector):
        element = self.driver.find_element_by_xpath(selector)
        if element:
            print 'Do something complex which I want to test'


x = ClassName()
when(x.driver).find_element_by_xpath('//dvi').thenReturn(mock())

```
Then I could not figure out an easy way to mock the  `element = self.driver.find_element_by_xpath(selector)` line.  I did try several ways with `when` or other ways to define the `driver`, but all of them ended with different type of errors. Usually with `AttributeError: 'NoneType' object has no attribute 'find_element_by_xpath'` How the code should be changed that the mocking would work?

**Comment by kaste** [comment]
Assuming `ClassName` is the class/object you're testing. Hm... 

```
    x = ClassName()
    driver = mock()
    el = mock()
    when(driver).find_element_by_xpath('//dvi').thenReturn(el)
    x.driver = driver

```` 

Since you have a `create_driver` on `x` you probably have to patch that one to do the right thing.

**Comment by aaltat** [comment]
Why I did not see that one. Thanks from help.
