### ISSUE TITLE
Support installation using Conda?

### ISSUE THREAD

**Issue by hans-permana** [kaste/mockito-python#14]
Hi there, I am really excited to use this library in Python. I have used it plenty of time in Java. Just one question, would installing through Conda environment be supported at some point? It would really simplify my Travis/Appveyor build.

**Comment by kaste** [comment]
I don't know Conda.

**Comment by kaste** [comment]
Ok, I found Conda 😄 

But as I see, this a curated package manager, so they pull whatever they want. However, they state that you can just `pip` whatever you want. https://conda.io/docs/user-guide/tasks/manage-pkgs.html#installing-non-conda-packages

So, I don't think this is actionable.

**Comment by kaste** [comment]
Closing due to lack of response.
