### ISSUE TITLE
Numpy arrays as when() arguments

### ISSUE THREAD

**Issue by Chris-hughes10** [kaste/mockito-python#28]
When using a numpy array as an argument to when() a value error is raised with the following message:

"ValueError: The truth value of an array with more than one element is ambiguous."

which is caused by the compare function in invocation.py.

It would be good to be able to pass array types to when(), which would be evaluated using .all() during comparison.

**Comment by kaste** [comment]
Hi! 

There is a numpy testfile here https://github.com/kaste/mockito-python/blob/master/tests/numpy_test.py

Can you write a failing test for it to get it starting?

**Comment by kaste** [comment]
stranded
