### ISSUE TITLE
Documentation: Mocking instances, not just classes

### ISSUE THREAD

**Issue by lsloan** [kaste/mockito-python#4]
In the walkthrough, you show how to mock the Dog class, which affects all instances of Dog until `unstub()` is used.  I think it's also important to show that a single instance of a class can be mocked.  Add to the documentation examples from https://code.google.com/archive/p/mockito-python/ that show mocking a single instance (rex) of Dog.

**Comment by kaste** [comment]
It's here http://pythonhosted.org/mockito/nutshell.html at least. Open for PRs as well.

**Comment by kaste** [comment]
I updated the walk-through.
