### ISSUE TITLE
resetting a mock?

### ISSUE THREAD

**Issue by attila123** [kaste/mockito-python#40]
Hi, thanks for this excellent library.

If I see correctly, there is no way of resetting a mock. Could you please add?
The closest thing I found is clear_invocations() in class Mock. But the examples always use mock(), not Mock().

Update: I guess I found it:

```
mockito.forget_invocations(my_mock)
```

**Comment by kaste** [comment]
Yes, `forget_invocations` is probably what you want.  The uppercase `Mock` is actually an implementation detail and should not be used, only use the lowercased functions.
