### ISSUE TITLE
no attributes in dummy objects since 1.3.2

### ISSUE THREAD

**Issue by vladak** [kaste/mockito-python#57]
Normally I'd ask about this in Discussions, however they do not seem to be enabled for this project so I am misusing the issue. Since 1.3.2 (including) there has been some change in behavior. 

In 1.3.0 everything is fine:
```
>>> import requests
>>> from mockito import mock
>>> m = mock(spec=requests.Response)
>>> m.status_code
functools.partial(<function remembered_invocation_builder at 0x107096790>, <mockito.mocking.Mock object at 0x1063ebe80>, 'status_code')
>>> 
```
however in 1.3.2 there was some change:
```
>>> import requests
>>> from mockito import mock
>>> m = mock(spec=requests.Response)
>>> m.status_code
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/venv/lib/python3.9/site-packages/mockito/mocking.py", line 286, in __getattr__
    raise AttributeError(
AttributeError: 'Dummy' has no attribute 'status_code' configured
```
which prevents the usual use cases. This is on Python 3.9.13 on macOS however happens also elsewhere.

**Comment by kaste** [comment]
I'm closing.  Sorry for the unfortunate breaking change 💇‍♂️

**Comment by vladak** [comment]
> I'm closing. Sorry for the unfortunate breaking change 💇‍♂️

No worries and thanks !

**Comment by kaste** [comment]
Oops, I did not close.
