### ISSUE TITLE
Backwards incompatable change between version 0.7.1 and 1.0.0

### ISSUE THREAD

**Issue by aaltat** [kaste/mockito-python#7]
In version 0.7.1 this used to work:
```
from mockito import mock

class ClassName(mock):
```
But in version 1.0.1 it says:
```
Traceback (most recent call last):
  File "/path/to/test/test_something.py", line 108, in test_create_something
    class ClassName(mock):
TypeError: Error when calling the metaclass bases
    function() argument 1 must be code, not str
```
Is this expected and I should change how my unit test work, or is this bug in mockito which could be fixed in some time frame?

**Comment by kaste** [comment]
`mock` is a function now. A factory for dummy objects. What's your usecase. Subclassing the old v<0.7 `Mock` class seems weird.

**Comment by kaste** [comment]
Isn't what you do here, the same as:

     def FakeWebDriver(some_arg=None):
        capt_data['some_arg'] = some_arg
        capt_data['webdriver'] = mock()

❓

**Comment by aaltat** [comment]
Well I am the current maintainer of the project, but those unit test where written quite a long time ago by someone who is not anymore involved in the project. I don't know what use case the original writer did have in mind. But it also looks funny for my eyes, specially because the mockito documentation tells to do it differently.

Your suggestions looks quite good one and I will try it out.

**Comment by kaste** [comment]
If that works out, you can get probably rid of `capt_data`.

    # FakeWebDriver seems to be a factory not a driver
    factory = mock()
    driver = mock()
    when(factory).__call__(some_arg=1).thenReturn(driver)
    # no need to assert `some_arg` gets passed bc mockito implicitly does that
    # if you get the `driver` back at the other end, `some_arg` must have been passed.
    assert bm._current_browser() == driver

And if that works out you could try to patch 'in' the factory:

    driver = mock()
    with when(selenium.webdriver, strict=False).FakeWebDriver(some_arg=1).thenReturn(driver):
        ...

Something like this _could_ work; obv I don't know the details of your project.

**Comment by aaltat** [comment]
Thanks from the pointers. I definitely need to give that a try.

Because this looks like a problem in my project I am closing the issue.

**Comment by aaltat** [comment]
Thanks from the help, the last example works perfectly.
