### ISSUE TITLE
TypeError: return_() got multiple values for argument 'value' 

### ISSUE THREAD

**Issue by surfer190** [kaste/mockito-python#82]
Seeing an error arising when using `value` as a keyword argument to a mockito `when`.

In `producer.py`:

```
def send(value):
    return value
```

In `mocking_check.py`:

```
from mockito import when

import producer

when(producer).send(value="test").thenReturn("Nope")

print(producer.send(value="test")
```

When running this the output is: `TypeError: return_() got multiple values for argument 'value' `

Result expected: `Nope`

Anyone know why this is the case. Attempting to mock a method with a similar signature - it worked but failed as soon as the `value` kwarg was introduced.

**Comment by kaste** [comment]
That's a good bug.  Good as in embarrassing 😬

**Comment by kaste** [comment]
Should be fixed in v1.5.1

**Comment by kaste** [comment]
Thanks for reporting

**Comment by surfer190** [comment]
Thanks for fix and maintaining the project. 👍
