### ISSUE TITLE
__eq__ bug

### ISSUE THREAD

**Issue by Wouter1** [kaste/mockito-python#85]
comparing two (different) mock objects with ```__eq__``` returns an object (not None) which makes it behave as "True". 

Expected behaviour: IMHO ```a.__eq__(b)``` should return True if ```a is b```, else False. Or, raise an exception if you really want to avoid this case. But I see no reason to raise on this

Actual: ```a.__eq__(b)``` returns ```NotImplemented``` (an class instance). Which basically means True in python, as anything except None evaluates to True in logical context. 

How to reproduce:
install mockito 1.5.1 (FYI 1.4.0 has the same behaviour)

```
from mockito import mock
a=mock()
b=mock()
a.__eq__(b)
NotImplemented
1 if a.__eq__(b) else 0
1
```
The line with the if expression shows that ```a.__eq__(b)``` effectively evaluates as True (in python everything not None is True)

**Comment by kaste** [comment]
Well, yeah, sort of.  The unconfigured dumb `mock()` doesn't behave well for the dunder methods.  IIRC only `__call__` is defined by default.  

However, you could configure `a`

```
In [22]: a = mock({"__eq__": lambda x: 7})

In [23]: a.__eq__(2)
Out[23]: 7

In [24]: a == 2
Out[24]: 7

In [25]: a == a
Out[25]: 7
```

Unfortunately `when(a).__eq__` doesn't work. so that would be worthwhile to investigate IMO.

Other than that, it works as expected for the typical case:

```
In [27]: a = mock()

In [28]: a == 2
Out[28]: False

In [29]: a == a
Out[29]: True

In [30]: b = mock()

In [31]: a == b
Out[31]: False
```  

so I'm not comppletely sure what you're trying to do here.  I.e. how's your real code look like?

**Comment by Wouter1** [comment]
Thanks for the workaround. Are there more pitfalls I need to be aware of?

I'm usually using ```__eq__``` instead of == because of the differences, and ```__eq__``` is what I really want in most cases. Maybe this difference between == and ```__eq__``` is a python bug, I dont know, as most pages say they behave equal, but as you see they don't.

>how's your real code look like
I'm mocking a simple object with mock. Then later somewhere in my production code I call __eq__ on the (now mocked) object.

Very specifically this is the code that breaks in my case; all bid objects have been mocked (but not sure how that helps you)
```
 if vote.getBid().__eq__(bid):
    return vote
```

Regarding the problem with ```when(a).__eq__```, yes I noticed more issues also eg with ```when(a).__repr__()``` for instance. It seems __repr__ is applied immediately instead of postponed.

**Comment by Wouter1** [comment]
BTW how do I use your workaround if I want to mock a class? Like

```
class A: 
  pass

b=mock(A, {"__eq__": lambda x: 7})
```

(this doesn't work, the ```__eq__``` is not used)

**Comment by kaste** [comment]
It's `a = mock({"__eq__": lambda x: 7}, A)` iirc.  (Usually you use `when` or - since that doesn't work here - `when2` when patching classes.)

What are the differences you're after between `__eq__` and `==`?

**Comment by Wouter1** [comment]
Ah, the argument order. Thanks!

>What are the differences you're after between __eq__ and ==?

I had some specific issues with == some 2 years ago, related to comparing classes I think. I can't remember exactly anymore but something like super()==MyClass versus super().__eq__(MyClass). There were more related issues, but it's long ago. After that I decided to use __eq__ everywhere to avoid these what seem to me python bugs

**Comment by kaste** [comment]
That's a bit vague to leave the standards path to be honest.  We have the dunders to implement a certain behavior for custom classes, not for the users of such classes.  🤷‍♀️ 

I close the issue as there isn't much to do, I think.

**Comment by Wouter1** [comment]
You don't have to rely on my vague memories

As my example also showed, ```__eq__``` and == are not behaving equal. That might be sufficient for you to take action

**Comment by Wouter1** [comment]
BTW I still can't get it quite working
```
from typing import Set
from mockito import mock, when

class Bid:
  def getIssues(self) -> Set[str]:
   return set()


bid:Bid = mock({"__eq__": lambda x: False}, strict=True, spec=Bid)

when(bid).getIssues().thenReturn(set())

```

gives

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/PythonVenvs/geniusweb1targz/lib/python3.8/site-packages/mockito/invocation.py", line 344, in __call__
    self.ensure_mocked_object_has_method(self.method_name)
  File "/tmp/PythonVenvs/geniusweb1targz/lib/python3.8/site-packages/mockito/invocation.py", line 331, in ensure_mocked_object_has_method
    raise InvocationError(
mockito.invocation.InvocationError: You tried to stub a method 'getIssues' the object (<DummyBid id=140275673611424>) doesn't have.

```

**Comment by Wouter1** [comment]
Just to be clear about that difference
```
>>> a=mock()
>>> a==2
False
>>> a.__eq__(2)
NotImplemented

```

**Comment by kaste** [comment]
Yes, but for above `class A: pass`.  

```
In [44]: A().__eq__(2)
Out[44]: NotImplemented

In [45]: A() == 2
Out[45]: False
```

so that seems to be as python wants it to behave.

**Comment by Wouter1** [comment]
@kaste can this ticket be re-opened at least till there is a properly working workaround?

**Comment by kaste** [comment]
> Don't you think that's a python bug?

Nah, it's likely the protocol here.  Implementers of `__eq__` should probably return 
`NotImplemented` for unknown comparisons.  

> It seems that doesn't work.

I have the following working:

```
In [1]: from mockito import *

In [2]: class A: pass

In [3]: a = mock({"__eq__": lambda x: 7}, A)

In [4]: a.__eq__(2)
Out[4]: 7

In [5]: a == 2
Out[5]: 7
```

> What I need is something like
> 
> `a = mock({"eq": lambda self,x: self is x}, A)`

You maybe need this but you don't want this as it makes the mock too complicated
for a test run.  

You could use `when2` (because `when` doesn't work)

```
In [17]: a = mock(A)

In [18]: when2(a.__eq__, 4).thenReturn(7)
Out[18]: <mockito.invocation.AnswerSelector at 0x23dbf917770>

In [19]: a.__eq__(2)
InvocationError:
Called but not expected:

    __eq__(2)

Stubbed invocations are:

    __eq__(4)

In [20]: a.__eq__(4)
Out[20]: 7
```
