### ISSUE TITLE
Patching built-in/extension types

### ISSUE THREAD

**Issue by betabandido** [kaste/mockito-python#9]
I am having problems patching `io.BytesIO`. When doing:

        bytesIO_mock = mock(strict=True)
        when(bytesIO_mock).getvalue().thenReturn('data')
        patch(BytesIO.__new__, lambda: bytesIO_mock)

I am getting the following error:

    def set_method(self, method_name, new_method):
    >       setattr(self.mocked_obj, method_name, new_method)
    E       TypeError: can't set attributes of built-in/extension type '_io.BytesIO'
        
    /venv/lib/python3.6/site-packages/mockito/mocking.py:74: TypeError`

Am I doing anything wrong, or is this a current limitation?

The following link contains a more detailed description of the issue:
http://stackoverflow.com/questions/43031393/how-to-patch-built-in-extension-types-in-python-using-mockito

**Comment by kaste** [comment]
Try `when(io).BytesIO().thenReturn(...)` or similar `patch(io.BytesIO, lambda...)`. Let me know if that works ☺️.

**Comment by kaste** [comment]
Closing due to lack of response.

**Comment by betabandido** [comment]
I was not able to try your suggestion until today. And, it works! Thanks :)
